namespace CloudStates;


/* 
    Well, it's fun to write out bytes bit by bit, but I'm pretty sure enums support this out of the box lol
    // TODO: Test later. 
*/
[Flags]
public enum CloudFlags : byte
{
    CLIENT_QUIT,
    CLIENT_REGISTER_REQUEST,
    CLIENT_LOGIN_REQUEST,
    CLIENT_SENDING_LOGIN_INFO,
    CLIENT_SENDING_REGISTRATION_INFO,
    CLIENT_VIEW_CLOUD_STORAGE,
    CLIENT_TO_DASHBOARD, // Later, when returning from chat.
    CLIENT_UPLOAD_REQUEST,
    CLIENT_DOWNLOAD_REQUEST,
    CLIENT_TO_CHAT,
    SERVER_OK,
    SERVER_USERNAME_TAKEN,
    SERVER_USERNAME_DOESNT_EXIST,
    SERVER_PASSWORD_INCORRECT,
    SERVER_INCORRECT_CREDENTIALS_STRUCTURE,
    SERVER_QUIT_CONNECTION,
    SERVER_PASSWORD_TOO_LONG,
    SERVER_USERNAME_TOO_LONG,
    SERVER_TOO_MANY_ATTEMPTS,
    SERVER_CLOUD_STORAGE_FILE_LIST,
    SERVER_KICKED_DUE_TO_INACTIVITY,
    SERVER_UNEXPECTED_SERVER_ERROR,
    SERVER_FILE_TOO_BIG,
    SERVER_FILENAME_TOO_LONG,
    SERVER_DISALLOWED_FILE_TYPE,
    SERVER_DOWNLOAD_ERROR,
    SERVER_NO_TOKENS,
    SERVER_UPLOAD_ACCEPTED,
    SERVER_UPLOAD_FAILED,
    SERVER_UPLOAD_SUCCESSFUL,
    SERVER_FILE_DOESNT_EXIST_ON_SERVER,
    SERVER_DOWNLOAD_COMPLETE,
    SERVER_DOWNLOAD_COMING,
    SERVER_REQUEST_TOO_LONG,
    SERVER_QUEUE_POSITION,
    SERVER_ALREADY_LOGGED_IN,
    SERVER_CLIENT_CHAT_MESSAGE,
}
